app:
  name: "{{cookiecutter.project_slug}}"
  env: "development"

logging:
  level: "info"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

mysql:
  user: "root"
  password: "example"
  host: "localhost"
  port: 3306
  database: "{{cookiecutter.project_slug}}"
